### ISSUE TITLE
Runtime error while running demo

### ISSUE THREAD

**Issue by santhu937** [shubhtuls/factored3d#22]
hi, I'm getting runtime error while running cli_demo.py, I ran on CPU by removing coda() calls and used pytorch 0.2.0 and python 2.7

Traceback (most recent call last):
  File "cli_demo.py", line 55, in <module>
    objects, layout = tester.predict_factored3d()
  File "/Users/santhosh/Documents/factored3d/../factored3d/demo/demo_utils.py", line 210, in predict_factored3d
    (self.input_imgs_fine, self.input_imgs, self.rois))
  File "/Users/santhosh/Documents/factored3d/../factored3d/nnutils/oc_net.py", line 216, in forward
    roi_img_feat = self.roi_pool.forward(img_feat_fine, rois_inp)
  File "/Users/santhosh/Documents/factored3d/../factored3d/nnutils/roi_pool_py.py", line 49, in forward
    torch.max(data[:, hstart:hend, wstart:wend], 1)[0], 1)[0].view(-1)
  File "/Users/santhosh/Desktop/iisc/san/lib/python2.7/site-packages/torch/autograd/variable.py", line 85, in __setitem__
    return SetItem.apply(self, key, value)
  File "/Users/santhosh/Desktop/iisc/san/lib/python2.7/site-packages/torch/autograd/_functions/tensor.py", line 43, in forward
    i._set_index(ctx.index, value)
RuntimeError: inconsistent tensor size, expected tensor [256] and src [512] to have the same number of elements, but got 256 and 512 elements respectively at /Users/soumith/code/builder/wheel/pytorch-src/torch/lib/TH/generic/THTensorCopy.c:86

**Comment by santhu937** [comment]
Figured out, use python 2.7 n pytorch 0.2.0

thank you
