### ISSUE TITLE
Error when running on CPU

### ISSUE THREAD

**Issue by j-jelly** [shubhtuls/factored3d#5]
Hi,
I am trying to run "cli_demo.py" on my system which does not have any gpu. Is there any way to run it on cpu only?

This is the (partial) error log I'm getting when running cli_demo.py:
```

Traceback (most recent call last):
  File "cli_demo.py", line 32, in <module>
    tester.init_testing()
  File "/home/jelly/factored3d/../factored3d/nnutils/test_utils.py", line 97, in init_testing
    self.define_model()
  File "/home/jelly/factored3d/../factored3d/demo/demo_utils.py", line 131, in define_model
    self.load_oc3d_model()
  File "/home/jelly/factored3d/../factored3d/demo/demo_utils.py", line 91, in load_oc3d_model
    self.oc3d_model = self.oc3d_model.cuda(device_id=self.opts.gpu_id)
.
.
.
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

```

**Comment by shubhtuls** [comment]
Hi,
Unfortunately, the current code assumes GPU support. However, it should be possible to edit it to use cpu only - this would require simply commenting out all the '.cuda()' calls.
