### ISSUE TITLE
Error Running cli-demo.py

### ISSUE THREAD

**Issue by qasimz** [shubhtuls/factored3d#9]
when I am running cli_demo.py   I am getting following error
rm: cannot remove '/home/qasim/factored3d/demo/../cachedir/rendering/dwr_shape_ft/*.obj': No such file or directory
Traceback (most recent call last):
  File "cli_demo.py", line 56, in <module>
    img_factored_cam, img_factored_novel = renderer.render_factored3d(objects, layout)
  File "/home/qasim/factored3d/../factored3d/demo/demo_utils.py", line 278, in render_factored3d
    return self.render_visuals(self.mesh_dir)
  File "/home/qasim/factored3d/../factored3d/demo/demo_utils.py", line 270, in render_visuals
    im_view1 = scipy.misc.imread(osp.join(png_dir, 'render_000.png'))
  File "/home/qasim/factored3d/venv/local/lib/python2.7/site-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/home/qasim/factored3d/venv/local/lib/python2.7/site-packages/scipy/misc/pilutil.py", line 164, in imread
    im = Image.open(name)
  File "/home/qasim/factored3d/venv/local/lib/python2.7/site-packages/PIL/Image.py", line 2548, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '/home/qasim/factored3d/demo/../cachedir/rendering/dwr_shape_ft/rendering/render_000.png'

**Comment by shubhtuls** [comment]
Hi,
The first error 'rm: cannot remove ..' is fine. This occurs because the rm command attempts to remove the existing saved meshes, but if you're running the code for the first time, there will be no existing meshes.

I think the error is related to blender not existing/working on your system. A couple of questions to verify this -
1) After the code crashes, are there saved '.obj' files in '/home/qasim/factored3d/demo/../cachedir/rendering/dwr_shape_ft/' ?
2) Do you have a 'bpy.so' in 'factored3d/renderer/blender/bpy/' ?
3) The rendering code is calling [this function](https://github.com/shubhtuls/factored3d/blob/master/renderer/utils.py#L79-L82). Can you print the 'cmd' that gets run in this function call? Try running the command from command line and let me know the output.

**Comment by qasimz** [comment]
Answers to your questions

1. Yes I have two '.obj' files (codes.obj & layout.obj)
2. I also have 'bpy.so' file
3. I removed the line that you asked and run it from withing python, I am getting the same error. I didn't understand to run the command from command line that's why I used the alternate option.

**Comment by shubhtuls** [comment]
Yes, i'm sure the final error is the same. But if you removed '>> /dev/null 2>&1', the call 'os.system(cmd)' should have printed additional stuff too. Can you please describe that output.

**Comment by qasimz** [comment]
The output is below. I thing I am missing python 3.4

sh: 1: python3.4: not found
Traceback (most recent call last):
  File "cli_demo.py", line 56, in <module>
    img_factored_cam, img_factored_novel = renderer.render_factored3d(objects, layout)
  File "/home/qasim/factored3d/../factored3d/demo/demo_utils.py", line 278, in render_factored3d
    return self.render_visuals(self.mesh_dir)
  File "/home/qasim/factored3d/../factored3d/demo/demo_utils.py", line 270, in render_visuals
    im_view1 = scipy.misc.imread(osp.join(png_dir, 'render_000.png'))
  File "/home/qasim/factored3d/venv/local/lib/python2.7/site-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/home/qasim/factored3d/venv/local/lib/python2.7/site-packages/scipy/misc/pilutil.py", line 164, in imread
    im = Image.open(name)
  File "/home/qasim/factored3d/venv/local/lib/python2.7/site-packages/PIL/Image.py", line 2548, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '/home/qasim/factored3d/demo/../cachedir/rendering/dwr_shape_ft/rendering/render_000.png'

**Comment by shubhtuls** [comment]
Yes, that sounds correct. You should install python 3.4. Alternately, you can try substituting 'python3.4' with 'python3' if you have a different python3 version - I think that should work too but I'm not sure.

**Comment by qasimz** [comment]
python3 cli_demo.py 
Traceback (most recent call last):
  File "cli_demo.py", line 8, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

**Comment by qasimz** [comment]
after running this comand pip install torchvision visdom dominate

Collecting torchvision
  Using cached https://files.pythonhosted.org/packages/ca/0d/f00b2885711e08bd71242ebe7b96561e6f6d01fdb4b9dcf4d37e2e13c5e1/torchvision-0.2.1-py2.py3-none-any.whl
Collecting visdom
  Using cached https://files.pythonhosted.org/packages/0e/f2/27b5d7c34b718afb355587d4e0c1f9108e925db4c0c932e935ba01051efd/visdom-0.1.7.tar.gz
Collecting dominate
  Using cached https://files.pythonhosted.org/packages/43/b2/3b7d67dd59dab93ae08569384b254323516e8868b453eea5614a53835baf/dominate-2.3.1.tar.gz
Collecting six (from torchvision)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting numpy (from torchvision)
  Using cached https://files.pythonhosted.org/packages/c0/e7/08f059a00367fd613e4f2875a16c70b6237268a1d6d166c6d36acada8301/numpy-1.14.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting torch (from torchvision)
  Downloading https://files.pythonhosted.org/packages/df/a4/7f5ec6e9df1bf13f1881353702aa9713fcd997481b26018f35e0be85faf7/torch-0.4.0-cp27-cp27mu-manylinux1_x86_64.whl (484.0MB)
    99% |████████████████████████████████| 484.0MB 505kB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/lib/python2.7/dist-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 432, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 380, in read
    data = self._fp.read(amt)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 63, in read
    self._close()
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/serialize.py", line 87, in dumps
    ).encode("utf8"),
MemoryError

**Comment by shubhtuls** [comment]
It seems like you have trouble installing the standard pytorch package. The [pytorch repo](https://github.com/pytorch/pytorch) would probably be a better place to find people who've faced similar issues.

**Comment by KnightOfTheMoonlight** [comment]
@shubhtuls  Hi, from the above, so python2.7 is not working for your project?

**Comment by KnightOfTheMoonlight** [comment]
@shubhtuls  could u put every environment settings in the root 'readMe' file?

**Comment by KnightOfTheMoonlight** [comment]
@qasimz  As what I can see from the log, your system is using python2.7, but that system cmd is using python3.4.

**Comment by pavan4** [comment]
Hi, 

I could not use the compiled `bpy.so` as it references `libGLEW1.10` and `Ubuntu 16.04` references `libGLEW1.13`

I compiled blender from source and generated the `bpy.so` and replaced the file in the folder.  I edited the utils folder etc and upon running I get the following error - 

Command: 


`python3.5 /home/ubuntu/factored3d/renderer/blender/render_dir_script.py  --obj_dir /home/ubuntu/factored3d/demo/../cachedir/rendering/dwr_shape_ft --out_dir /home/ubuntu/factored3d/demo/../cachedir/rendering/dwr_shape_ft/rendering --r 2 --delta_theta 30 --sz_x 320 --sz_y 2`

Output: 


`Color management: using fallback mode for management
Segmentation fault (core dumped)`

There are no other error messages apart from this. Not entirely sure what is causing the seg fault.

**Comment by santhu937** [comment]
@pavan4 even I have same problem, were u able to solve the error
